OrdererOrgs:
  - Name: OrdererOrg
    Domain: orderer.com
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer

PeerOrgs:
  - Name: KshrdOrg
    Domain: kshrd.com
    EnableNodeOUs: true
    Specs:
      - Hostname: devpeer
    Users:
      Count: 3

  - Name: KosignOrg
    Domain: kosign.com
    EnableNodeOUs: true
    Specs:
      - Hostname: devpeer
    Users:
      Count: 3

